### ISSUE TITLE
not compatible with redmine_issues_tree

### ISSUE THREAD

**Issue by archonwang** [zitec/redmine_blocked_reason#14]
@zitec ,
installed redmine_issues_tree, and foun they're not compatible each other, please help to check it. 
(https://github.com/Loriowar/redmine_issues_tree)
my environment is redmine 3.3.4

Thanks.

error logs
```
Started POST "/projects/demo/issues_trees/redirect_with_params" for 192.168.20.231 at 2017-04-25 19:34:04 +0800
Processing by IssuesTreesController#redirect_with_params as JSON
  Parameters: {"utf8"=>"?", "set_filter"=>"1", "f"=>["status_id", ""], "op"=>{"status_id"=>"o"}, "c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "group_by"=>"", "t"=>["estimated_hours", "spent_hours", ""], "project_id"=>"demo"}
  Current user: hui.wang (id=8)
Completed 200 OK in 12ms (Views: 0.2ms | ActiveRecord: 2.6ms)
Started GET "/projects/demo/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=" for 192.168.20.231 at 2017-04-25 19:34:04 +0800
Processing by IssuesTreesController#tree_index as HTML
  Parameters: {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
  Current user: hui.wang (id=8)
STATEMENT projects.id = 1 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT projects.id = 1 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (0.7ms)
Read fragment views/queries/filter/user-8/2017-04-20T06:45:51Z/2017-04-25 07:14:16 UTC/e42c5980be4ccd0f7205b2df55f850cf (0.2ms)
  Rendered plugins/redmine_performance/app/views/queries/_filters.html.erb (8.5ms)
  Rendered queries/_columns.html.erb (3.5ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (1104.2ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml (1115.0ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml within layouts/base (1136.9ms)
Completed 500 Internal Server Error in 1249ms (ActiveRecord: 21.5ms)

ActionView::Template::Error (undefined method `render_blocked_reason_tag' for #<#<Class:0x000000051f33f8>:0x007fe87d8ff648>):
    12:     = link_to issue.id, controller: 'issues', action: 'show', id: issue
    13:   - cols = query.inline_columns.map do |column|
    14:     - unless column.value(issue) == issue.id
    15:       - content_tag 'td', column_content(column, issue), class: column.css_classes
    16:   = raw cols.join
  plugins/redmine_blocked_reason/lib/redmine_blocked_reason/patches/queries_helper_patch.rb:17:in `column_value_with_blocked_reason_tag'
  app/helpers/queries_helper.rb:134:in `column_content'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:15:in `block in _e25dc3bf17a7b13a4e1e22be921192a7'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `map'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `_e25dc3bf17a7b13a4e1e22be921192a7'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:24:in `block (2 levels) in _0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `each'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `block in _0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:11:in `_0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:75:in `_424ff0b1702ea603d118f238d7499477'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/projects/demo/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=" for 192.168.20.231 at 2017-04-25 19:34:05 +0800
Processing by IssuesTreesController#tree_index as */*
  Parameters: {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
  Current user: hui.wang (id=8)
STATEMENT projects.id = 1 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
STATEMENT projects.id = 1 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_plain_view.html.haml (0.7ms)
Read fragment views/queries/filter/user-8/2017-04-20T06:45:51Z/2017-04-25 07:14:16 UTC/e42c5980be4ccd0f7205b2df55f850cf (0.3ms)
  Rendered plugins/redmine_performance/app/views/queries/_filters.html.erb (8.1ms)
  Rendered queries/_columns.html.erb (3.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml (1543.3ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml (1553.8ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml within layouts/base (1575.3ms)
Completed 500 Internal Server Error in 1689ms (ActiveRecord: 22.6ms)

ActionView::Template::Error (undefined method `render_blocked_reason_tag' for #<#<Class:0x000000051f33f8>:0x0000000b491028>):
    12:     = link_to issue.id, controller: 'issues', action: 'show', id: issue
    13:   - cols = query.inline_columns.map do |column|
    14:     - unless column.value(issue) == issue.id
    15:       - content_tag 'td', column_content(column, issue), class: column.css_classes
    16:   = raw cols.join
  plugins/redmine_blocked_reason/lib/redmine_blocked_reason/patches/queries_helper_patch.rb:17:in `column_value_with_blocked_reason_tag'
  app/helpers/queries_helper.rb:134:in `column_content'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:15:in `block in _a853942285bf843368126a11f0fa1ab5'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `map'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `_a853942285bf843368126a11f0fa1ab5'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:24:in `block (2 levels) in _0720dd6620541a2bdf5d9b240fc02ed8'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `each'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `block in _0720dd6620541a2bdf5d9b240fc02ed8'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:11:in `_0720dd6620541a2bdf5d9b240fc02ed8'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:75:in `_c26dbd1fbdffad29a86e2dd7a2fec8b9'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by archonwang** [comment]
debug error log

```
An ActionView::Template::Error occurred in issues_trees#tree_index:
 
  undefined method `render_blocked_reason_tag' for #<#<Class:0x000000051f33f8>:0x007fe87d8ff648>
  plugins/redmine_blocked_reason/lib/redmine_blocked_reason/patches/queries_helper_patch.rb:17:in `column_value_with_blocked_reason_tag'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/projects/demo/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
  * HTTP Method: GET
  * IP address : 192.168.20.231
  * Parameters : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""], "controller"=>"issues_trees", "action"=>"tree_index"}
  * Timestamp  : 2017-04-25 11:34:05 UTC
  * Server : jira
  * Rails root : /opt/redmine-3.3
  * Process: 15598
 
-------------------------------
Session:
-------------------------------
 
  * session id: "e870bc050bb0ac26dc091b657bcaebcf"
  * data: {"session_id"=>"e870bc050bb0ac26dc091b657bcaebcf",
   "user_id"=>8,
   "tk"=>"ec7365cd3a37b45eaa4fc81f9afd82ac20b9e283",
   "sudo_timestamp"=>1493114426,
   "_csrf_token"=>"jQ9eALcbN296PytKko9bnyaEpVmtu53uWexV++zVLec=",
   "query"=>
    {:project_id=>1,
     :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
     :group_by=>"",
     :column_names=>nil,
     :totalable_names=>[:estimated_hours, :spent_hours]},
   "issues_index_sort"=>"id:desc",
   "timelog_index_sort"=>"spent_on:desc",
   "timesheets_show_sort"=>"spent_on:desc",
   "current_timesheet"=>
    {:query=>
      {:filters=>{"spent_on"=>{:operator=>"w", :values=>[""]}},
       :group_by=>"spent_on",
       :column_names=>nil,
       :totalable_names=>[:hours]}},
   "issues_trees_tree_index_sort"=>"id:desc"}
 
-------------------------------
Environment:
-------------------------------
 
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _redmine_session=Y2hFUjFuSzNRcUVKc1ZyTE5UNXhYQjZxdzZrSXV3WkJHRi9LeXRqMW44V2ZWOThVbXpWYVZvZFllWlVKWDRxZkxnL3FFSnIyNVdIVVR4RkkwVUN1dW83VTBYakErT3dvMzJKbGUwNWtpblExcUhSb0tBekllTDMyZms0UjVLZVNkSlFzNnJpd1dEc3lOblNNRE1KZlFXMEpvMFZVUlNyQUE4TDN0d2NveGVFK0pkSTNORldBeCtHak1yQmxSUXZ5UDk5c2h2MURPTDg0bVkwUHFzZ2lVTnFIV3RYeUhtTDhncXBrREtPQkRJV0dOVWFZam5kNzlmMXJ2TDMvNGhXZWFqTGt5citpT0tvdGd4OGxKMUcwVHRyaGNFVjJvejgrZ0dtcEZoTHQ3UklxMlEyVDFCOTdoSXc2ZkVSTmxZYmpJUkpEZys1YkwxR2t4YUxpa01JdHlGYzI0czVZYWJMQ05CUEZqaTJLd0VYYTQxZWNHMHcyNjBBVkNCRlJWMGNCVmpZY1lxc0tsb1NmNit1dTNHd1ZSayszb0tPVWFyZEVZbHJEV0RISVZBWFdneC82Q2tGWjFYb1VuUWNuOUYwcEQ5RFBxYVdrK1p1aTl1WjNrcWpoZUJHR0ZicDRVTUhoRnh6M0dpN2dIVmVESEltd1NmUWR1Rnc2YldqbGQ5YTBXaTFEZ3paNi8rTUpWMy9Wd1N5SW1UWWtvNEJvcndFNnpYNzZNY3JPWlhQUEszbzFDc0N4ZVlTMklvK2xoMGJ0SUJhNHJLcDIzSGJsc2llMkRDV0dHS0hZOGFZQ3I3RElYdyt6SGJhR0ZudFhtaytCTWkvVTFXV01PbWJqK0p1d1FwK3VYY0JvUWViNlE0ZTdxZEtYUXdsa2FONXJSSDFVR0FQNmcxb3U1R1VKMUVOcHB5Mktmb2RVeGVoM2gzai9xR1BvMFNaTUlZbjJFZUMzc2JCQkpQSzllck5sQVNoNkZNQU1xWWpKck5CMGowTldnU0RBRXd2bS9TSWdMQTlzdTE2WitpSGoxZzdVL00wVUxCK0xCd2tQVm5qeHFialZUTldWMlNEL2YwU2lObjd3NHlMWmVUV1VacmNOeVF2OGVVVy9OQlRYbzduWGdaM0E3RzZMeGMwaytGK3IyLzY5MEtadmpra2lLOWY5SVpPY2R1THRFNUJMeTBOdDNZY3hYOUd5ZnE0VkZ0UFpqN3hoQm1ldllBPT0tLVdNY2dKNUQ4WHk0Q3AyMkVmOXJEMnc9PQ%3D%3D--1147ebc58491d0c19fd31d1efc7097109cfe8556
  * HTTP_HOST                                      : 192.168.1.41
* HTTP_REFERER : http://192.168.1.41/projects/demo/issues
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * ORIGINAL_FULLPATH                              : /projects/demo/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /projects/demo/issues_trees/tree_index
  * QUERY_STRING                                   : c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
  * REMOTE_ADDR                                    : 192.168.20.231
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /projects/demo/issues_trees/tree_index
  * REQUEST_URI                                    : /projects/demo/issues_trees/tree_index?c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
  * ROUTES_36680840_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<IssuesTreesController:0x007fe898154f18>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000004aea390>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007fe87ee0a2e0>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000000aa5c300>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x000000045da4b8>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 192.168.20.231
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x000000041cdaf0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=3925320872312671123>]
  * action_dispatch.request.parameters             : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""], "controller"=>"issues_trees", "action"=>"tree_index"}
  * action_dispatch.request.path_parameters        : {:controller=>"issues_trees", :action=>"tree_index", :project_id=>"demo"}
  * action_dispatch.request.query_parameters       : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"e870bc050bb0ac26dc091b657bcaebcf", "user_id"=>8, "tk"=>"ec7365cd3a37b45eaa4fc81f9afd82ac20b9e283", "sudo_timestamp"=>1493114426, "_csrf_token"=>"jQ9eALcbN296PytKko9bnyaEpVmtu53uWexV++zVLec=", "query"=>{:project_id=>1, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:estimated_hours, :spent_hours]}, "issues_index_sort"=>"id:desc", "timelog_index_sort"=>"spent_on:desc", "timesheets_show_sort"=>"spent_on:desc", "current_timesheet"=>{:query=>{:filters=>{"spent_on"=>{:operator=>"w", :values=>[""]}}, :group_by=>"spent_on", :column_names=>nil, :totalable_names=>[:hours]}}, "issues_trees_tree_index_sort"=>"id:desc"}
  * action_dispatch.request_id                     : c07c97e0-17f6-466f-807a-cef2ddbe09e1
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000045f6910>
  * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x007fe8782a9e10>
  * rack.errors                                    : #<IO:0x0000000174d5a0>
  * rack.input                                     : #<StringIO:0x007fe8782aa5e0>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_redmine_session"=>"Y2hFUjFuSzNRcUVKc1ZyTE5UNXhYQjZxdzZrSXV3WkJHRi9LeXRqMW44V2ZWOThVbXpWYVZvZFllWlVKWDRxZkxnL3FFSnIyNVdIVVR4RkkwVUN1dW83VTBYakErT3dvMzJKbGUwNWtpblExcUhSb0tBekllTDMyZms0UjVLZVNkSlFzNnJpd1dEc3lOblNNRE1KZlFXMEpvMFZVUlNyQUE4TDN0d2NveGVFK0pkSTNORldBeCtHak1yQmxSUXZ5UDk5c2h2MURPTDg0bVkwUHFzZ2lVTnFIV3RYeUhtTDhncXBrREtPQkRJV0dOVWFZam5kNzlmMXJ2TDMvNGhXZWFqTGt5citpT0tvdGd4OGxKMUcwVHRyaGNFVjJvejgrZ0dtcEZoTHQ3UklxMlEyVDFCOTdoSXc2ZkVSTmxZYmpJUkpEZys1YkwxR2t4YUxpa01JdHlGYzI0czVZYWJMQ05CUEZqaTJLd0VYYTQxZWNHMHcyNjBBVkNCRlJWMGNCVmpZY1lxc0tsb1NmNit1dTNHd1ZSayszb0tPVWFyZEVZbHJEV0RISVZBWFdneC82Q2tGWjFYb1VuUWNuOUYwcEQ5RFBxYVdrK1p1aTl1WjNrcWpoZUJHR0ZicDRVTUhoRnh6M0dpN2dIVmVESEltd1NmUWR1Rnc2YldqbGQ5YTBXaTFEZ3paNi8rTUpWMy9Wd1N5SW1UWWtvNEJvcndFNnpYNzZNY3JPWlhQUEszbzFDc0N4ZVlTMklvK2xoMGJ0SUJhNHJLcDIzSGJsc2llMkRDV0dHS0hZOGFZQ3I3RElYdyt6SGJhR0ZudFhtaytCTWkvVTFXV01PbWJqK0p1d1FwK3VYY0JvUWViNlE0ZTdxZEtYUXdsa2FONXJSSDFVR0FQNmcxb3U1R1VKMUVOcHB5Mktmb2RVeGVoM2gzai9xR1BvMFNaTUlZbjJFZUMzc2JCQkpQSzllck5sQVNoNkZNQU1xWWpKck5CMGowTldnU0RBRXd2bS9TSWdMQTlzdTE2WitpSGoxZzdVL00wVUxCK0xCd2tQVm5qeHFialZUTldWMlNEL2YwU2lObjd3NHlMWmVUV1VacmNOeVF2OGVVVy9OQlRYbzduWGdaM0E3RzZMeGMwaytGK3IyLzY5MEtadmpra2lLOWY5SVpPY2R1THRFNUJMeTBOdDNZY3hYOUd5ZnE0VkZ0UFpqN3hoQm1ldllBPT0tLVdNY2dKNUQ4WHk0Q3AyMkVmOXJEMnc9PQ==--1147ebc58491d0c19fd31d1efc7097109cfe8556"}
  * rack.request.cookie_string                     : _redmine_session=Y2hFUjFuSzNRcUVKc1ZyTE5UNXhYQjZxdzZrSXV3WkJHRi9LeXRqMW44V2ZWOThVbXpWYVZvZFllWlVKWDRxZkxnL3FFSnIyNVdIVVR4RkkwVUN1dW83VTBYakErT3dvMzJKbGUwNWtpblExcUhSb0tBekllTDMyZms0UjVLZVNkSlFzNnJpd1dEc3lOblNNRE1KZlFXMEpvMFZVUlNyQUE4TDN0d2NveGVFK0pkSTNORldBeCtHak1yQmxSUXZ5UDk5c2h2MURPTDg0bVkwUHFzZ2lVTnFIV3RYeUhtTDhncXBrREtPQkRJV0dOVWFZam5kNzlmMXJ2TDMvNGhXZWFqTGt5citpT0tvdGd4OGxKMUcwVHRyaGNFVjJvejgrZ0dtcEZoTHQ3UklxMlEyVDFCOTdoSXc2ZkVSTmxZYmpJUkpEZys1YkwxR2t4YUxpa01JdHlGYzI0czVZYWJMQ05CUEZqaTJLd0VYYTQxZWNHMHcyNjBBVkNCRlJWMGNCVmpZY1lxc0tsb1NmNit1dTNHd1ZSayszb0tPVWFyZEVZbHJEV0RISVZBWFdneC82Q2tGWjFYb1VuUWNuOUYwcEQ5RFBxYVdrK1p1aTl1WjNrcWpoZUJHR0ZicDRVTUhoRnh6M0dpN2dIVmVESEltd1NmUWR1Rnc2YldqbGQ5YTBXaTFEZ3paNi8rTUpWMy9Wd1N5SW1UWWtvNEJvcndFNnpYNzZNY3JPWlhQUEszbzFDc0N4ZVlTMklvK2xoMGJ0SUJhNHJLcDIzSGJsc2llMkRDV0dHS0hZOGFZQ3I3RElYdyt6SGJhR0ZudFhtaytCTWkvVTFXV01PbWJqK0p1d1FwK3VYY0JvUWViNlE0ZTdxZEtYUXdsa2FONXJSSDFVR0FQNmcxb3U1R1VKMUVOcHB5Mktmb2RVeGVoM2gzai9xR1BvMFNaTUlZbjJFZUMzc2JCQkpQSzllck5sQVNoNkZNQU1xWWpKck5CMGowTldnU0RBRXd2bS9TSWdMQTlzdTE2WitpSGoxZzdVL00wVUxCK0xCd2tQVm5qeHFialZUTldWMlNEL2YwU2lObjd3NHlMWmVUV1VacmNOeVF2OGVVVy9OQlRYbzduWGdaM0E3RzZMeGMwaytGK3IyLzY5MEtadmpra2lLOWY5SVpPY2R1THRFNUJMeTBOdDNZY3hYOUd5ZnE0VkZ0UFpqN3hoQm1ldllBPT0tLVdNY2dKNUQ4WHk0Q3AyMkVmOXJEMnc9PQ%3D%3D--1147ebc58491d0c19fd31d1efc7097109cfe8556
  * rack.request.query_hash                        : {"c"=>["tracker", "subject", "status", "author", "assigned_to", "priority", "updated_on", "due_date"], "f"=>["status_id", ""], "group_by"=>"", "op"=>{"status_id"=>"o"}, "project_id"=>"demo", "set_filter"=>"1", "t"=>["estimated_hours", "spent_hours", ""]}
  * rack.request.query_string                      : c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=status&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=priority&c%5B%5D=updated_on&c%5B%5D=due_date&f%5B%5D=status_id&f%5B%5D=&group_by=&op%5Bstatus_id%5D=o&project_id=demo&set_filter=1&t%5B%5D=estimated_hours&t%5B%5D=spent_hours&t%5B%5D=
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007fe898ef0168>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fe898ef0118>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/redmine_blocked_reason/lib/redmine_blocked_reason/patches/queries_helper_patch.rb:17:in `column_value_with_blocked_reason_tag'
  app/helpers/queries_helper.rb:134:in `column_content'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:15:in `block in _e25dc3bf17a7b13a4e1e22be921192a7'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `map'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_node.html.haml:13:in `_e25dc3bf17a7b13a4e1e22be921192a7'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:24:in `block (2 levels) in _0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `each'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:23:in `block in _0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_issues_tree/app/views/issues_trees/_tree_list.html.haml:11:in `_0b0eef26e4f32c9291e516482e7affcd'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_issues_tree/app/views/issues_trees/tree_index.html.haml:75:in `_424ff0b1702ea603d118f238d7499477'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
```
