### ISSUE TITLE
Unable to delete block statuses

### ISSUE THREAD

**Issue by zcatalinz** [zitec/redmine_blocked_reason#9]
1. Go to plugins settings : settings/plugin/redmine_blocked_reason
2. Create a new status
3. Delete it.

Actual:
You are unable to delete it.

Expected:
You should be able to delete it.

**Comment by archonwang** [comment]
error log

```
Started DELETE "/blocked_reason_types/2" for 192.168.20.231 at 2017-04-25 19:50:59 +0800
Processing by BlockedReasonTypesController#destroy as HTML
  Parameters: {"authenticity_token"=>"P/ZVfwrlWK30Lhv0E+QN21mtrfj34MwDHxC/RYewG/2y+Qt/vf5vwo4RML6Ba1ZEfykIoVpbUe1G/Oq+a2U2Gg==", "id"=>"2"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.9ms)

NoMethodError (undefined method `removed=' for #<BlockedReasonType:0x007fe864129810>):
  plugins/redmine_blocked_reason/app/controllers/blocked_reason_types_controller.rb:35:in `destroy'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/blocked_reason_types/2" for 192.168.20.231 at 2017-04-25 19:51:00 +0800

ActionController::RoutingError (No route matches [GET] "/blocked_reason_types/2"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.0) lib/thin/connection.rb:84:in `catch'
  thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.0) lib/thin/connection.rb:50:in `block in process'
  eventmachine (1.2.3) lib/eventmachine.rb:1076:in `call'
  eventmachine (1.2.3) lib/eventmachine.rb:1076:in `block in spawn_threadpool'

```

**Comment by archonwang** [comment]
debug error log

```
A NoMethodError occurred in blocked_reason_types#destroy:
 
  undefined method `removed=' for #<BlockedReasonType:0x007fe864129810>
  plugins/redmine_blocked_reason/app/controllers/blocked_reason_types_controller.rb:35:in `destroy'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/blocked_reason_types/2
  * HTTP Method: DELETE
  * IP address : 192.168.20.231
  * Parameters : {"_method"=>"delete", "authenticity_token"=>"P/ZVfwrlWK30Lhv0E+QN21mtrfj34MwDHxC/RYewG/2y+Qt/vf5vwo4RML6Ba1ZEfykIoVpbUe1G/Oq+a2U2Gg==", "controller"=>"blocked_reason_types", "action"=>"destroy", "id"=>"2"}
  * Timestamp  : 2017-04-25 11:50:59 UTC
  * Server : jira
  * Rails root : /opt/redmine-3.3
  * Process: 15598
 
-------------------------------
Session:
-------------------------------
 
  * session id: "e870bc050bb0ac26dc091b657bcaebcf"
  * data: {"session_id"=>"e870bc050bb0ac26dc091b657bcaebcf",
   "user_id"=>8,
   "tk"=>"ec7365cd3a37b45eaa4fc81f9afd82ac20b9e283",
   "sudo_timestamp"=>1493114426,
   "_csrf_token"=>"jQ9eALcbN296PytKko9bnyaEpVmtu53uWexV++zVLec=",
   "query"=>
    {:project_id=>1,
     :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
     :group_by=>nil,
     :column_names=>nil,
     :totalable_names=>[:estimated_hours, :spent_hours]},
   "issues_index_sort"=>"id:desc",
   "timelog_index_sort"=>"spent_on:desc",
   "timesheets_show_sort"=>"spent_on:desc",
   "current_timesheet"=>
    {:query=>
      {:filters=>{"spent_on"=>{:operator=>"w", :values=>[""]}},
       :group_by=>"spent_on",
       :column_names=>nil,
       :totalable_names=>[:hours]}},
   "issues_trees_tree_index_sort"=>"id:desc",
   "flash"=>{"discard"=>["notice"], "flashes"=>{"notice"=>"顶层菜单已更新。"}}}
 
-------------------------------
Environment:
-------------------------------
 
  * CONTENT_LENGTH                                 : 142
  * CONTENT_TYPE                                   : application/x-www-form-urlencoded
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
  * HTTP_CACHE_CONTROL                             : max-age=0
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _redmine_session=ZHNOQlpMenZtU0Z4Q3BsdXdVQnlGN1NuRjczaFArTTdjeGRsVEZJditubkk5VmFONnVIUjhNZVcyYjhzY1N4bWp4T3RaQWU2ZUNnSFlhblI0T3VZYzZiTnA1aHFweWFyL2U0QVZMZmhUUUlMaGQveXVYengwMGV5UzIzc2k4VU1sVURmNGZIT2Fqb29zb3hyeUdHdERLQ0lWV3BKKzRZbkhvc1Boa2xjSDBQUW5udnErRUxGT29iMmVJZVR2clo3ZU9pZnRMa1lITjJIajY0NFVGYWtxUnhVUUcwVkg1SjB2Zi9meTBYT2o0aTY2SGVNRnYrK3dGYUx6ZkJ5OCtGckdtd0pMOTg0MzRFL1d5Y1A3U1dWbXpKcFZ2OWZQbjV0TlI2aW00OGJlN3kxSHo0TGlnMHpPYWcyeTk1YzB4aUFnejh0R1B3RWIvU3FyNjd6WXlpRkREaDV4R3NndEhUMVF6SW1LTDd2K29WMGJSYVdTanNJM09SZW5CVno1czZncHBSSWdkYzVDcC96UExkUjkrNCs4cG1DTjBSaUw5b0R6cFEzVHhQdW4rSTg1RDBocU1HVGVDSldWT3dDdFBESm5FUDB3M1djOWpUV1ZrSlRWZ2NFbFgzWkRoVVhYczBvQUFweVJjWnZSd2tLM3BqWU9pNGdudklZWGZ3WUZDR0FOWmU3NExFY1loaHltQ1EvUSs0UnZQR3BQUVEwSmE3Q0luRGVsOHFmb25iQ3VYMGJJVjJodG11RFpLU1BkM2FiZXBSTlFUSnhrQzVkY01DM0hvTXh5ZVQzbWUvZHEyTzVZcGYyUVJ2dHA2SmoyaXpLM0cra1lES1U5YnZ6YTQzUS90c05GT01CWGtFYVBIcWxub3Z1dFlLVkNHelhBRFlGQjZKWWE2U3puUUEzdkNtc1lnRXFiZEJOZFd1VzAyKzlzaW5HaTdFeTU2alIvVDUwYmZadjM2bm5Bb2R1RkVDMHNKWC9oV2JiYUxVdnUvYzFidTJWM1U1Sm5FTlA4dHVHNmxxNS91V1VjNW00UUhjUzhITEpOMHlLa2Y0WG9xbU5zOUJsR3BVVk96NzJSSE4wQWp3RXFUdlc3VVF3RE15M3BVbWJJMVVZK09rQTlNaGNuSXN5Njd0UE4xbjNWMENwb3NvcEg0enpsSmZKVXJFUVJFNzFaTVNrd3l4ektMOWRzcFZERjhhbG5LK1JQNFc0UDNsWXBRT2xVLy9TaTFjTWZJdHdLWHRoVktBdUV1aVNQR3pwQWtSaXZ0a2tVR1VmMEIrV3AvRU1ycVc3M2NzMGxzZjNvM2dkRXBvb2RQNlJkR3QyandUTDVXNmhMdkI3USt5Y2ZyNWZNYkJvdy9waFVuY2ZyMEljR0ZVOUJyQW9ZcFM2NEdtR0Npd0FadTZla1Z0SEU4VFl2WjQ9LS1hQXhpUTlMUzVaMUZmRXVtcWpiNENnPT0%3D--25fd8206a9e0fde7a8daafc547e7a2e227f01acb
  * HTTP_HOST                                      : 192.168.1.41
* HTTP_ORIGIN : http://192.168.1.41
* HTTP_REFERER : http://192.168.1.41/settings/plugin/redmine_blocked_reason
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * ORIGINAL_FULLPATH                              : /blocked_reason_types/2
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /blocked_reason_types/2
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 192.168.20.231
  * REQUEST_METHOD                                 : DELETE
  * REQUEST_PATH                                   : /blocked_reason_types/2
  * REQUEST_URI                                    : /blocked_reason_types/2
  * ROUTES_36680840_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<BlockedReasonTypesController:0x007fe8640b6630>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000004aea390>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007fe8641006e0>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000000aa5c300>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x000000045da4b8>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 192.168.20.231
  * action_dispatch.request.content_type           : application/x-www-form-urlencoded
  * action_dispatch.request.formats                : [#<Mime::Type:0x000000041cdaf0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=3925320872312671123>]
  * action_dispatch.request.parameters             : {"_method"=>"delete", "authenticity_token"=>"P/ZVfwrlWK30Lhv0E+QN21mtrfj34MwDHxC/RYewG/2y+Qt/vf5vwo4RML6Ba1ZEfykIoVpbUe1G/Oq+a2U2Gg==", "controller"=>"blocked_reason_types", "action"=>"destroy", "id"=>"2"}
  * action_dispatch.request.path_parameters        : {:controller=>"blocked_reason_types", :action=>"destroy", :id=>"2"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {"_method"=>"delete", "authenticity_token"=>"P/ZVfwrlWK30Lhv0E+QN21mtrfj34MwDHxC/RYewG/2y+Qt/vf5vwo4RML6Ba1ZEfykIoVpbUe1G/Oq+a2U2Gg=="}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"e870bc050bb0ac26dc091b657bcaebcf", "user_id"=>8, "tk"=>"ec7365cd3a37b45eaa4fc81f9afd82ac20b9e283", "sudo_timestamp"=>1493114426, "_csrf_token"=>"jQ9eALcbN296PytKko9bnyaEpVmtu53uWexV++zVLec=", "query"=>{:project_id=>1, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:estimated_hours, :spent_hours]}, "issues_index_sort"=>"id:desc", "timelog_index_sort"=>"spent_on:desc", "timesheets_show_sort"=>"spent_on:desc", "current_timesheet"=>{:query=>{:filters=>{"spent_on"=>{:operator=>"w", :values=>[""]}}, :group_by=>"spent_on", :column_names=>nil, :totalable_names=>[:hours]}}, "issues_trees_tree_index_sort"=>"id:desc", "flash"=>{"discard"=>["notice"], "flashes"=>{"notice"=>"顶层菜单已更新。"}}}
  * action_dispatch.request_id                     : 364d4c7b-fd46-4d2e-8e01-0652fe214f05
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000045f6910>
  * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x007fe875ea5528>
  * rack.errors                                    : #<IO:0x0000000174d5a0>
  * rack.input                                     : #<StringIO:0x007fe875ea5ed8>
  * rack.methodoverride.original_method            : POST
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_redmine_session"=>"ZHNOQlpMenZtU0Z4Q3BsdXdVQnlGN1NuRjczaFArTTdjeGRsVEZJditubkk5VmFONnVIUjhNZVcyYjhzY1N4bWp4T3RaQWU2ZUNnSFlhblI0T3VZYzZiTnA1aHFweWFyL2U0QVZMZmhUUUlMaGQveXVYengwMGV5UzIzc2k4VU1sVURmNGZIT2Fqb29zb3hyeUdHdERLQ0lWV3BKKzRZbkhvc1Boa2xjSDBQUW5udnErRUxGT29iMmVJZVR2clo3ZU9pZnRMa1lITjJIajY0NFVGYWtxUnhVUUcwVkg1SjB2Zi9meTBYT2o0aTY2SGVNRnYrK3dGYUx6ZkJ5OCtGckdtd0pMOTg0MzRFL1d5Y1A3U1dWbXpKcFZ2OWZQbjV0TlI2aW00OGJlN3kxSHo0TGlnMHpPYWcyeTk1YzB4aUFnejh0R1B3RWIvU3FyNjd6WXlpRkREaDV4R3NndEhUMVF6SW1LTDd2K29WMGJSYVdTanNJM09SZW5CVno1czZncHBSSWdkYzVDcC96UExkUjkrNCs4cG1DTjBSaUw5b0R6cFEzVHhQdW4rSTg1RDBocU1HVGVDSldWT3dDdFBESm5FUDB3M1djOWpUV1ZrSlRWZ2NFbFgzWkRoVVhYczBvQUFweVJjWnZSd2tLM3BqWU9pNGdudklZWGZ3WUZDR0FOWmU3NExFY1loaHltQ1EvUSs0UnZQR3BQUVEwSmE3Q0luRGVsOHFmb25iQ3VYMGJJVjJodG11RFpLU1BkM2FiZXBSTlFUSnhrQzVkY01DM0hvTXh5ZVQzbWUvZHEyTzVZcGYyUVJ2dHA2SmoyaXpLM0cra1lES1U5YnZ6YTQzUS90c05GT01CWGtFYVBIcWxub3Z1dFlLVkNHelhBRFlGQjZKWWE2U3puUUEzdkNtc1lnRXFiZEJOZFd1VzAyKzlzaW5HaTdFeTU2alIvVDUwYmZadjM2bm5Bb2R1RkVDMHNKWC9oV2JiYUxVdnUvYzFidTJWM1U1Sm5FTlA4dHVHNmxxNS91V1VjNW00UUhjUzhITEpOMHlLa2Y0WG9xbU5zOUJsR3BVVk96NzJSSE4wQWp3RXFUdlc3VVF3RE15M3BVbWJJMVVZK09rQTlNaGNuSXN5Njd0UE4xbjNWMENwb3NvcEg0enpsSmZKVXJFUVJFNzFaTVNrd3l4ektMOWRzcFZERjhhbG5LK1JQNFc0UDNsWXBRT2xVLy9TaTFjTWZJdHdLWHRoVktBdUV1aVNQR3pwQWtSaXZ0a2tVR1VmMEIrV3AvRU1ycVc3M2NzMGxzZjNvM2dkRXBvb2RQNlJkR3QyandUTDVXNmhMdkI3USt5Y2ZyNWZNYkJvdy9waFVuY2ZyMEljR0ZVOUJyQW9ZcFM2NEdtR0Npd0FadTZla1Z0SEU4VFl2WjQ9LS1hQXhpUTlMUzVaMUZmRXVtcWpiNENnPT0=--25fd8206a9e0fde7a8daafc547e7a2e227f01acb"}
  * rack.request.cookie_string                     : _redmine_session=ZHNOQlpMenZtU0Z4Q3BsdXdVQnlGN1NuRjczaFArTTdjeGRsVEZJditubkk5VmFONnVIUjhNZVcyYjhzY1N4bWp4T3RaQWU2ZUNnSFlhblI0T3VZYzZiTnA1aHFweWFyL2U0QVZMZmhUUUlMaGQveXVYengwMGV5UzIzc2k4VU1sVURmNGZIT2Fqb29zb3hyeUdHdERLQ0lWV3BKKzRZbkhvc1Boa2xjSDBQUW5udnErRUxGT29iMmVJZVR2clo3ZU9pZnRMa1lITjJIajY0NFVGYWtxUnhVUUcwVkg1SjB2Zi9meTBYT2o0aTY2SGVNRnYrK3dGYUx6ZkJ5OCtGckdtd0pMOTg0MzRFL1d5Y1A3U1dWbXpKcFZ2OWZQbjV0TlI2aW00OGJlN3kxSHo0TGlnMHpPYWcyeTk1YzB4aUFnejh0R1B3RWIvU3FyNjd6WXlpRkREaDV4R3NndEhUMVF6SW1LTDd2K29WMGJSYVdTanNJM09SZW5CVno1czZncHBSSWdkYzVDcC96UExkUjkrNCs4cG1DTjBSaUw5b0R6cFEzVHhQdW4rSTg1RDBocU1HVGVDSldWT3dDdFBESm5FUDB3M1djOWpUV1ZrSlRWZ2NFbFgzWkRoVVhYczBvQUFweVJjWnZSd2tLM3BqWU9pNGdudklZWGZ3WUZDR0FOWmU3NExFY1loaHltQ1EvUSs0UnZQR3BQUVEwSmE3Q0luRGVsOHFmb25iQ3VYMGJJVjJodG11RFpLU1BkM2FiZXBSTlFUSnhrQzVkY01DM0hvTXh5ZVQzbWUvZHEyTzVZcGYyUVJ2dHA2SmoyaXpLM0cra1lES1U5YnZ6YTQzUS90c05GT01CWGtFYVBIcWxub3Z1dFlLVkNHelhBRFlGQjZKWWE2U3puUUEzdkNtc1lnRXFiZEJOZFd1VzAyKzlzaW5HaTdFeTU2alIvVDUwYmZadjM2bm5Bb2R1RkVDMHNKWC9oV2JiYUxVdnUvYzFidTJWM1U1Sm5FTlA4dHVHNmxxNS91V1VjNW00UUhjUzhITEpOMHlLa2Y0WG9xbU5zOUJsR3BVVk96NzJSSE4wQWp3RXFUdlc3VVF3RE15M3BVbWJJMVVZK09rQTlNaGNuSXN5Njd0UE4xbjNWMENwb3NvcEg0enpsSmZKVXJFUVJFNzFaTVNrd3l4ektMOWRzcFZERjhhbG5LK1JQNFc0UDNsWXBRT2xVLy9TaTFjTWZJdHdLWHRoVktBdUV1aVNQR3pwQWtSaXZ0a2tVR1VmMEIrV3AvRU1ycVc3M2NzMGxzZjNvM2dkRXBvb2RQNlJkR3QyandUTDVXNmhMdkI3USt5Y2ZyNWZNYkJvdy9waFVuY2ZyMEljR0ZVOUJyQW9ZcFM2NEdtR0Npd0FadTZla1Z0SEU4VFl2WjQ9LS1hQXhpUTlMUzVaMUZmRXVtcWpiNENnPT0%3D--25fd8206a9e0fde7a8daafc547e7a2e227f01acb
  * rack.request.form_hash                         : {"_method"=>"delete", "authenticity_token"=>"P/ZVfwrlWK30Lhv0E+QN21mtrfj34MwDHxC/RYewG/2y+Qt/vf5vwo4RML6Ba1ZEfykIoVpbUe1G/Oq+a2U2Gg=="}
  * rack.request.form_input                        : #<StringIO:0x007fe875ea5ed8>
  * rack.request.form_vars                         : [FILTERED]
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007fe87c2dfb88>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fe87c2dfb38>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/redmine_blocked_reason/app/controllers/blocked_reason_types_controller.rb:35:in `destroy'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
```
